### ISSUE TITLE
MenuWalkerなどを利用してサイドバーを刷新、ナビバーメニューを刷新(結果、NestedPages 3+の機能を利用)

### ISSUE THREAD

**Issue by toiee-kameda** [toiee-lab/kanso-general#50]
## 概要

- [ ] Walker_Nav_Menu を使って、使われるタグなどを刷新する
- [ ] 専用ウィジェットを作る（どのメニューを off-canvas sidebar に使うか、title、depthを指定できる）
- [ ] depth 以後のページは「ドロップダウンメニュー」とする
- [ ] メニューの起点のページの場合は「起点以外はドロップダウン状態」でいつでもアクセスできる

とにかく、使いやすいものにする。

参考情報

- [uikit 3.0 wordpress sidebar](https://gist.github.com/Dreamelf/d63b2a6a05236e66f31ee46e7f4d4482) Walker_Nav_Menu などがしっかり記述されている
- [custom nav walker のサンプル](https://gist.github.com/kosinix/5544535)

```
How to transform UIKit's navigation to a Wordpress wp_menu_nav navigation?

UIKits way of constructing nested navigations with <nav><ul><li >Main Menu<div><ul><li>Dropdown menu... is way beyond what wp_nav_menu is capable of by default. Are there any examples of how you implement it, probably using a custom walker?
翻訳
プラスワン 0 件
共有 0 回
一般公開で共有しています
Marco Sascha Sven Hoppe さんのプロフィール写真
Marco Sascha Sven Hoppe
I've written one a few months ago that you can use as a boilerplate. As you can see it's not fully implemented because I ditched WP for my project, but it should be enough to keep you going.

class custom_walker extends Walker_Nav_Menu
	{
	      function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0)
	      {
	           global $wp_query;
	           $indent = ( $depth ) ? str_repeat( "\t", $depth ) : '';
	
	           $class_names = $value = '';
	
	           $classes = empty( $item->classes ) ? array() : (array) $item->classes;
	
	           $class_names = join( ' ', apply_filters( 'nav_menu_css_class', array_filter( $classes ), $item ) );
	           $class_names = ' class="'. esc_attr( $class_names ) . '"';
	
	           $output .= $indent . '<li id="menu-item-'. $item->ID . '"' . $value . $class_names .' data-uk-tooltip="{pos:\'bottom\'}" title="' . esc_attr($item->description) . '">';
	
//	           $attributes  = ! empty( $item->attr_title ) ? ' title="'  . esc_attr( $item->attr_title ) .'"' : '';
//	           $attributes .= ! empty( $item->target )     ? ' target="' . esc_attr( $item->target     ) .'"' : '';
//	           $attributes .= ! empty( $item->xfn )        ? ' rel="'    . esc_attr( $item->xfn        ) .'"' : '';
	           $attributes .= ! empty( $item->url )        ? ' href="'   . esc_attr( $item->url        ) .'"' : '';
//	           $description  = ! empty( $item->description ) ? '<span>'.esc_attr( $item->description ).'</span>' : '';
	
	           if($depth != 0)
	           {
	                     $description = $append = $prepend = "";
	           }
	
	            $item_output = $args->before;
	            $item_output .= '<a'. $attributes .'>';
	            $item_output .= $args->link_before .$prepend.apply_filters( 'the_title', $item->title, $item->ID ).$append;
	            $item_output .= $description.$args->link_after;
	            $item_output .= '</a>';
	            $item_output .= $args->after;
	
	            $output .= apply_filters( 'walker_nav_menu_start_el', $item_output, $item, $depth, $args );
	            }
	}
翻訳

2014/11/18
Martin Betz さんのプロフィール写真
Martin Betz
Perfect! Thanks a million. I will try that one out. I wish UIKit's team would provide a way to share snippets like this and make those searchable...
```

---

## 概要

NestedPage 3+ は、色々と便利になった（2xもか？）。中でも、固定ページ一覧で「リンク」を扱えること。固定ページ一覧で、フォーラム、投稿、その他の投稿タイプへのリンクを設定できる。そして、これらの複合的な固定ページ一覧（階層化したもの）は、「メニュー」として同期できる。

つまり、「固定ページを中心として、メニューが作れる」のが、NestedPageの利点。

さらに、NestedPage は、メニューへの表示、非表示が設定できる。これらのことを最大限に利用すれば、「メニュー」をサイドバーに設定することで、固定ページを作ってリダイレクトするという無理なことを避けることが可能になる。

**取り組みたい！**

## NestedPage の仕様について

- Sync Menu をオンにしておかないといけない
- メニューから Hide をしても、子ページは表示される（これは、KANSOウィジェットも同じ）
- メニュー化する階層は選べない

## ToDo

- [ ] マニュアルの準備（お知らせをしっかりする）
- [ ] Nested Pageのメニューを使うので、CSSの調整をする
- [ ] 表示する階層数を設定できるようにする
- [ ] 親が「非表示」なら、子ページもhideする（できるかなー、面倒そうだ）
- [ ] 後方互換の確保
- [ ] 子要素のあり、なしでの高さのずれを修正 #40

**Comment by toiee-kameda** [comment]
KANSOページ目次Widgetと、メニューをマージして使う仕様とする。ポイントは「固定ページ」ではなく、リンクを挿入すること。リンクをうまくマージできさえすれば、OKかな。

あとは、「メニューのクラスを指定させる」のは一つだ。parent と accordion が使えれば、だいぶいいかもしれない。あとはアイコンか・・・。

[ ] リンクを目次にマージする
[ ] 固定ページのオプションで、クラスを指定できるようにする
[ ] 固定ページのオプションで、アイコンを指定できるようにする

本当は、NestedPages にフックがたくさんあれば、、、それでいいんだが。

**Comment by toiee-kameda** [comment]
WordPressのWalker などを変更することで対応する。
